# Standard GAP package smoke check; run with TestPackage("fermionAHSS").
gap> pages := koAHSS_batch(CyclicGroup(2), 0, 0, 1, 5);;
gap> Assert(0, Length(pages) = 5);
gap> expected := [[[0],[],[2]],[[],[]],[[2]],[],[]];;
gap> Assert(0, ForAll(pages, table -> table = expected));
gap> Assert(0, koAHSS_batch(CyclicGroup(2), 0, 0, 1) = expected);
gap> Assert(0, koAHSS_batch(CyclicGroup(2), 0, 0, -1) = [[[0]],[],[],[],[]]);
gap> Assert(0, koAHSS(CyclicGroup(2), 0, 0, 1).lines = [[[2],[],[2],fail,fail]]);
gap> R := ResolutionFiniteGroup(CyclicGroup(2),4);;
gap> B := koAHSSHAPSpace(R,koAHSSNaturalOperations());;
gap> Assert(0, koAHSS_batch(CyclicGroup(2),[1],[1],1,5) = koAHSSpages(B,[1],[1],1,5));
gap> Assert(0, Test(Filename(DirectoriesPackageLibrary("fermionAHSS","tst"),"display.tst"),rec(compareFunction:="uptowhitespace")));
gap> Assert(0, Test(Filename(DirectoriesPackageLibrary("fermionAHSS","tst"),"api.tst"),rec(compareFunction:="uptowhitespace")));
gap> Assert(0, Test(Filename(DirectoriesPackageLibrary("fermionAHSS","tst"),"integer_equations.tst"),rec(compareFunction:="uptowhitespace")));
gap> Assert(0, Test(Filename(DirectoriesPackageLibrary("fermionAHSS","tst"),"extension_transfer.tst"),rec(compareFunction:="uptowhitespace")));
gap> Read(Filename(DirectoriesPackageLibrary("fermionAHSS","tst"),"extension_primary_transport.g"));
gap> Read(Filename(DirectoriesPackageLibrary("fermionAHSS","tst"),"binary_tensors.g"));
gap> Read(Filename(DirectoriesPackageLibrary("fermionAHSS","tst"),"native_pages.g"));
gap> Assert(0, Test(Filename(DirectoriesPackageLibrary("fermionAHSS","tst"),"extensions.tst"),rec(compareFunction:="uptowhitespace")));
gap> Assert(0, Test(Filename(DirectoriesPackageLibrary("fermionAHSS","tst"),"stacking_extensions.tst"),rec(compareFunction:="uptowhitespace")));
gap> Assert(0, Test(Filename(DirectoriesPackageLibrary("fermionAHSS","tst"),"extension_lifts.tst"),rec(compareFunction:="uptowhitespace")));
gap> Assert(0, Test(Filename(DirectoriesPackageLibrary("fermionAHSS","tst"),"extension_equivalence.tst"),rec(compareFunction:="uptowhitespace")));
gap> Assert(0, Test(Filename(DirectoriesPackageLibrary("fermionAHSS","tst"),"extension_gauge_reduction.tst"),rec(compareFunction:="uptowhitespace")));
gap> Assert(0, Test(Filename(DirectoriesPackageLibrary("fermionAHSS","tst"),"extension_target_layer.tst"),rec(compareFunction:="uptowhitespace")));
gap> Assert(0, Test(Filename(DirectoriesPackageLibrary("fermionAHSS","tst"),"extension_prime_local.tst"),rec(compareFunction:="uptowhitespace")));
gap> Assert(0, Test(Filename(DirectoriesPackageLibrary("fermionAHSS","tst"),"extension_transfer_hooks.tst"),rec(compareFunction:="uptowhitespace")));
gap> Assert(0, Test(Filename(DirectoriesPackageLibrary("fermionAHSS","tst"),"extension_primary_rows.tst"),rec(compareFunction:="uptowhitespace")));
gap> Assert(0, Test(Filename(DirectoriesPackageLibrary("fermionAHSS","tst"),"extension_light_rows.tst"),rec(compareFunction:="uptowhitespace")));
