"""Exact degree <= 3 reduced power and the three-primary ko d5 term.

For a degree-three mod-three cocycle a with sign coefficients, P^1_s(a)
is evaluated by 19 integral triple-face terms, followed by reduction mod 3.
These terms are generated by the cyclic resolution diagonal, not fitted to
examples.  The generators obey d(e1)=(rho-1)e0, d(e2)=(1+rho+rho^2)e1;
rho moves the last tensor factor to the front with its Koszul sign.

Write D0 for the threefold Alexander--Whitney diagonal and h for the
tensor contraction of a simplex to its first vertex.  The finite recursion is

    Di(sigma) = h(Ri D(i-1)(sigma) + (-1)^i Di(boundary sigma)),
    Ri = rho-1 (i odd), 1+rho+rho^2 (i even).

It satisfies d Di - (-1)^i Di d = Ri D(i-1) integrally.  The standard
acyclic-carrier construction identifies it with the cyclic diagonal used
for reduced powers.  In the ordinary simplicial coboundary convention used
here, P^1 on inputs of degrees 2 and 3 is the pointwise triple evaluation of
D0 and D2, respectively.  The dual tensor sign is included in this statement;
adding May's normalization factor a second time would reverse degree 3.

Each factor is transported from its face's first vertex to the simplex's
first vertex.  The resulting coefficient system is Z_s tensor-cubed = Z_s.
The integral Bockstein is +d_s(standard lift)/3, and complexification gives
the ko coefficient 2 (c(alpha4)=2u^2).

Primary sources for the cyclic resolution and normalization:
  May, A general algebraic approach to Steenrod operations, sections 5, 7:
  https://www.math.uchicago.edu/~may/PAPERS/10.pdf
  Kaufmann--Medina-Mardones, Cochain level May--Steenrod operations,
  sections 3, 5: https://arxiv.org/html/2010.02571
The accompanying tests check the integral diagonal identities, simplicial
degeneracies, P^1(uv)=uv^3 on BC3, the positive Bockstein, right suspension,
and nonzero sign transport.  No floating arithmetic or external dependency
is used.
"""

from collections import defaultdict
from fractions import Fraction
from functools import lru_cache

try:
    from .cochain_tools import Cochain, zero
except ImportError:  # Standalone unittest discovery from this directory.
    from cochain_tools import Cochain, zero


def _add(chain, term, coefficient):
    chain[term] += coefficient
    if not chain[term]:
        del chain[term]


def _rotate(chain):
    result = defaultdict(int)
    for (left, middle, right), coefficient in chain.items():
        parity = (len(right) - 1) * (len(left) + len(middle) - 2)
        _add(result, (right, left, middle), coefficient * (-1) ** parity)
    return result


def _map_vertices(chain, vertices, normalized=False):
    result = defaultdict(int)
    for factors, coefficient in chain.items():
        mapped = tuple(tuple(vertices[j] for j in face) for face in factors)
        if normalized and any(len(set(face)) != len(face) for face in mapped):
            continue
        _add(result, mapped, coefficient)
    return result


def _tensor_cone(chain):
    """h tensor 1 tensor 1 + projection tensor h tensor 1 + ... ."""
    result = defaultdict(int)
    for factors, coefficient in chain.items():
        for slot, face in enumerate(factors):
            if face[0] != 0:
                changed = ((0,),) * slot + ((0,) + face,) + factors[slot + 1:]
                _add(result, changed, coefficient)
            # A preceding projection kills every positive-dimensional chain.
            # Its surviving degree is zero, so no further Koszul sign occurs.
            if len(face) != 1:
                break
    return result


@lru_cache(None)
def cyclic_diagonal(index, dimension):
    """Return immutable (triple of faces, integer coefficient) terms of Di.

    This internal finite constructor is also exposed for identity audits.
    It supports only the bounds required by the degree-three operation.
    """
    if index not in (0, 1, 2) or not 0 <= dimension <= 8:
        raise ValueError("cyclic diagonal supports indices 0..2 and dimensions 0..8")
    if index == 0:
        return tuple(
            ((tuple(range(left + 1)), tuple(range(left, right + 1)),
              tuple(range(right, dimension + 1))), 1)
            for left in range(dimension + 1)
            for right in range(left, dimension + 1)
        )
    lower = dict(cyclic_diagonal(index - 1, dimension))
    source = defaultdict(int)
    for term, coefficient in _rotate(lower).items():
        _add(source, term, coefficient)
    if index % 2:
        for term, coefficient in lower.items():
            _add(source, term, -coefficient)
    else:
        for summand in (lower, _rotate(_rotate(lower))):
            for term, coefficient in summand.items():
                _add(source, term, coefficient)
    if dimension:
        previous = dict(cyclic_diagonal(index, dimension - 1))
        for omitted in range(dimension + 1):
            face = tuple(j for j in range(dimension + 1) if j != omitted)
            for term, coefficient in _map_vertices(previous, face).items():
                _add(source, term, (-1) ** (index + omitted) * coefficient)
    return tuple(sorted(_tensor_cone(source).items()))


@lru_cache(None)
def reduced_power_terms(input_degree):
    """The fixed triple-face formula for P^1 in input degree 2 or 3."""
    if input_degree not in (2, 3):
        raise ValueError("the nonzero reduced-power formula supports degrees 2 and 3")
    index = 2 * (input_degree - 2)
    return tuple(
        (factors, coefficient)
        for factors, coefficient in cyclic_diagonal(index, input_degree + 4)
        if all(len(face) == input_degree + 1 for face in factors)
    )


def _sign(s, edge):
    value = s(edge)
    if value not in (0, 1):
        raise ValueError("the sign twist must be a binary degree-one cocycle")
    return 1 - 2 * value


def signed_coboundary(cochain, s):
    """Ordinary positive simplicial coboundary with first-face transport."""
    if s.degree != 1:
        raise ValueError("the sign twist must have degree one")

    def evaluate(simplex):
        first = _sign(s, simplex[:2]) * cochain(simplex[1:])
        return first + sum(
            (-1) ** j * cochain(simplex[:j] + simplex[j + 1:])
            for j in range(1, len(simplex))
        )

    return Cochain(cochain.degree + 1, evaluate)


def reduced_power_1(a, s):
    """Return the standard 0,1,2 lift of P^1_s(a), for |a| <= 3.

    The caller supplies a normalized mod-three cocycle and a normalized
    binary sign cocycle, evaluated on tuples of simplex vertices.  Integral
    values of a are reduced modulo 3.  It is legitimate for a to be the
    reduction of an integral cocycle, but that assumption is not required.
    """
    if a.degree not in (0, 1, 2, 3) or s.degree != 1:
        raise ValueError("P^1_s requires input degree 0..3 and sign degree one")
    if a.degree < 2:
        return zero(a.degree + 4)
    terms = reduced_power_terms(a.degree)

    def evaluate(simplex):
        if len(simplex) != a.degree + 5:
            raise ValueError("simplex dimension does not match the reduced power")
        result = 0
        for factors, coefficient in terms:
            value = coefficient
            for face in factors:
                value *= a(tuple(simplex[j] for j in face)) % 3
                if not value:
                    break
                if face[0]:
                    value *= _sign(s, (simplex[0], simplex[face[0]]))
            result += value
        return result % 3

    return Cochain(a.degree + 4, evaluate, "P1_mod3_sign")


def beta_3_power_1(a, s):
    """Return the positive integral cocycle beta_{3,s} P^1_s(a)."""
    numerator = signed_coboundary(reduced_power_1(a, s), s)

    def evaluate(simplex):
        value = numerator(simplex)
        if value % 3:
            raise ArithmeticError("P^1_s input failed mod-three cocycle consistency")
        return value // 3

    return Cochain(a.degree + 5, evaluate, "beta3_P1_sign")


def tertiary_three_primary_phase(A, s):
    """A rational phase for 2 beta_{3,s} P^1_s rho_3(A), |A| <= 3.

    A is an integral sign cocycle.  For |A| <= 2 the cohomology operation
    vanishes (instability or the integral cubic lift), so choose phase zero.
    The input cocycle condition belongs to the defining-system validation.
    """
    if A.degree not in (0, 1, 2, 3) or s.degree != 1:
        raise ValueError("the ko three-primary correction supports input degrees 0..3")
    if A.degree < 3:
        return zero(A.degree + 4)
    power = reduced_power_1(A, s)
    return Cochain(7, lambda simplex: Fraction(2 * power(simplex), 3),
                   "ko_d5_three_primary_phase")


def tertiary_three_primary(A, s):
    """Integral representative of the ko correction, including its factor 2."""
    phase = tertiary_three_primary_phase(A, s)
    boundary = signed_coboundary(phase, s)

    def evaluate(simplex):
        value = boundary(simplex)
        if value.denominator != 1:
            raise ArithmeticError("the three-primary ko correction is not integral")
        return int(value)

    return Cochain(A.degree + 5, evaluate, "ko_d5_three_primary")
